version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
      build:
        docker:
          - image: circleci/node:14.15.0
        branches: 
          only: 
            - master
        steps:
          - add_ssh_keys:
            fingerprints:
              |
              3c:d3:d6:81:66:b5:f6:2b:be:78:41:f6:a5:f8:4d:9c 
          - checkout
          - run: npm install
          - run: npm run docs:build